# Generated by Django 5.1.6 on 2026-04-19 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='accountvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='accounts/video-thumbs/'),
        ),
        migrations.AddField(
            model_name='accountvideo',
            name='video_file',
            field=models.FileField(blank=True, upload_to='accounts/videos/'),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='hero_upload',
            field=models.ImageField(blank=True, upload_to='accounts/heroes/'),
        ),
        migrations.AlterField(
            model_name='accountvideo',
            name='embed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='gameaccount',
            name='hero_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gameaccount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='market.category'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('click', 'Click'), ('payme', 'Payme')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('order_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('external_id', models.CharField(blank=True, max_length=140)),
                ('provider_reference', models.CharField(blank=True, max_length=140)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='market.gameaccount')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
